default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: invoicing_development

test:
  <<: *default
  database: invoicing_test

production:
  <<: *default
  database: invoicing_production
  username: invoicing
  password: <%= ENV['INVOICING_DATABASE_PASSWORD'] %>
